name: Run Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
    - name: Run tests
      run: |
        chmod +x hva-skeleton/runtests_both.sh
        hva-skeleton/runtests_both.sh